import React from "react";
import Header from "../common/header";
import Footer from "../common/footer";
import Navbar from "../common/navbar";
import styles from "../styles/About.module.css"
import Image from 'next/image';
import Head from 'next/head';



const About = () => {
  return (
   <>
   <Head>
    <title>next about title</title>
    <meta name="description" content="Generated by create next app" />
   </Head>
    <div className={styles.about_text}>
      <h2>This is about file.</h2>
     <Image src='/hqdefault.jpg' width={400} height={100}/>
    </div>
    </>
  );
};

export default About;
